### ISSUE TITLE
KeyboardEvent is undefined (Angular 8 SSR)

### ISSUE THREAD

**Issue by DrewImm** [Agranom/ngx-material-timepicker#179]
After upgrading to version 4 of this package (and angular to version 8), I started to receive a build error. When compiling with server-side rendering in Angular 8, the build errors out. Downgrading back to version 3 seems to band-aid the situation.

```
> redacted@0.0.0 serve:ssr /home/redacted/Dev/redacted
> node dist/server

/home/redacted/Dev/redacted/dist/server.js:243106
        Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__metadata"])("design:paramtypes", [KeyboardEvent]),
                                                                                       ^

ReferenceError: KeyboardEvent is not defined
    at /home/redacted/Dev/redacted/dist/server.js:243106:88
    at Module.<anonymous> (/home/redacted/Dev/redacted/dist/server.js:243132:2)
    at __webpack_require__ (/home/redacted/Dev/redacted/dist/server.js:20:30)
    at Object.ngx-material-timepicker (/home/redacted/Dev/redacted/dist/server.js:154112:18)
    at __webpack_require__ (/home/redacted/Dev/redacted/dist/server.js:140208:30)
    at Module../src/app/assignment/assignment-modal/assignment-modal.component.ngfactory.js (/home/redacted/Dev/redacted/dist/server.js:144244:82)
    at __webpack_require__ (/home/redacted/Dev/redacted/dist/server.js:140208:30)
    at Module../src/app/app.server.module.ngfactory.js (/home/redacted/Dev/redacted/dist/server.js:143550:124)
    at __webpack_require__ (/home/redacted/Dev/redacted/dist/server.js:140208:30)
    at Module../src/main.server.ts (/home/redacted/Dev/redacted/dist/server.js:153566:90)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redacted@0.0.0 serve:ssr: `node dist/server`
npm ERR! Exit status 1
```

**Comment by Agranom** [comment]
I'll check

**Comment by Agranom** [comment]
Check this out https://stackoverflow.com/questions/55650575/angular-universal-referenceerror-keyboardevent-is-not-defined it seems that it might solve your issue.
