### ISSUE TITLE
"TypeError: Cannot read property 'kind' of undefined" with ng build

### ISSUE THREAD

**Issue by KirillTovpinets** [Agranom/ngx-material-timepicker#336]
Hi!

When running `ng build --configuration=production` my build crashed and the error pointed on ngx-material-timepicker.js file.

Here is the whole stack

```
ERROR in ./node_modules/ngx-material-timepicker/fesm2015/ngx-material-timepicker.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:230:35)
    at checkNodeForDecorators (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:53:21)
    at visitNodes (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16631:30)
    at Object.forEachChild (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16859:24)
    at transformer (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:39:16)
    at transformSourceFileOrBundle (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:67384:57)
    at transformation (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:83586:24)
    at transformRoot (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:83606:82)
    at Object.map (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:499:29)
    at Object.transformNodes (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:83593:30)
    at emitJsFileOrBundle (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:84089:32)
    at emitSourceFileOrBundle (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:84043:13)
    at forEachEmittedFile (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:83832:34)
    at Object.emitFiles (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:84026:9)
    at emitWorker (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:89951:33)
    at D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:89912:66
    at runWithCancellationToken (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:90002:24)
    at Object.emit (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:89912:20)
    at Object.transformJavascript (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\src\helpers\transform-javascript.js:111:13)
    at Object.buildOptimizer (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\src\build-optimizer\build-optimizer.js:119:35)
    at Object.buildOptimizerLoader (D:\Projects\Tempero\tempero-web\src\tempero-web\ClientApp\node_modules\@angular-devkit\build-optimizer\src\build-optimizer\webpack-loader.js:40:40)
```

**Comment by alikhaliutsin** [comment]
I have the same error with angular 8.1.3 and typeScript 3.4.5. But package with the version of [5.4.3](https://www.npmjs.com/package/ngx-material-timepicker/v/5.4.3) ng build works fine.

**Comment by Agranom** [comment]
Use the latest version (5.5.1)

**Comment by alikhaliutsin** [comment]
https://github.com/Agranom/ngx-material-timepicker/issues/332 - this helped me. Thx )

**Comment by KirillTovpinets** [comment]
Not working, unfortunately... I use angular 8.2.6, typescript 3.4.5 and ng build doesn't work with timepicker of 5.5.1 version

**Comment by alikhaliutsin** [comment]
> 
> 
> Not working, unfortunately... I use angular 8.2.6, typescript 3.4.5 and ng build doesn't work with timepicker of 5.5.1 version

I fixed it by upgrading to "@angular-devkit/build-angular": "^0.803.23",

**Comment by KirillTovpinets** [comment]
I've got build-angular of ~0.803.4 version...
