### ISSUE TITLE
ngx-timepicker-field issues with `min` parameter

### ISSUE THREAD

**Issue by Dschuli** [Agranom/ngx-material-timepicker#369]
Hi, I have to issues with the min parameter of the ngx-timepicker-field component (Angular 9,  ngx-material-timepicker  version 
5.5.3.

1. Keyboard input is blocked when parameter is set

2. Component throws an error when stepping below the limit.Error message:
```
{error: TypeError: Cannot read property 'time' of undefined
    at NgxTimepickerTimeControlComponent.push..…}error: TypeError: Cannot read property 'time' of undefined
    at NgxTimepickerTimeControlComponent.push../node_modules/ngx-material-timepicker/__ivy_ngcc__/fesm5/ngx-material-timepicker.js.NgxTimepickerTimeControlComponent.setAvailableTime (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:398572:77)
    at NgxTimepickerTimeControlComponent.push../node_modules/ngx-material-timepicker/__ivy_ngcc__/fesm5/ngx-material-timepicker.js.NgxTimepickerTimeControlComponent.ngOnChanges (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:398464:22)
    at NgxTimepickerTimeControlComponent.wrapOnChangesHook_inPreviousChangesStorage (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:50387:18)
    at callHook (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:33958:14)
    at callHooks (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:33924:17)
    at executeCheckHooks (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:33859:5)
    at selectIndexInternal (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:37254:17)
    at Module.ɵɵadvance (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:37233:5)
    at NgxTimepickerFieldComponent_Template (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:398399:64)
    at executeTemplate (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:38614:9)message: "Cannot read property 'time' of undefined"stack: "TypeError: Cannot read property 'time' of undefined↵    at NgxTimepickerTimeControlComponent.push../node_modules/ngx-material-timepicker/__ivy_ngcc__/fesm5/ngx-material-timepicker.js.NgxTimepickerTimeControlComponent.setAvailableTime (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:398572:77)↵    at NgxTimepickerTimeControlComponent.push../node_modules/ngx-material-timepicker/__ivy_ngcc__/fesm5/ngx-material-timepicker.js.NgxTimepickerTimeControlComponent.ngOnChanges (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:398464:22)↵    at NgxTimepickerTimeControlComponent.wrapOnChangesHook_inPreviousChangesStorage (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:50387:18)↵    at callHook (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:33958:14)↵    at callHooks (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:33924:17)↵    at executeCheckHooks (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:33859:5)↵    at selectIndexInternal (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:37254:17)↵    at Module.ɵɵadvance (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:37233:5)↵    at NgxTimepickerFieldComponent_Template (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:398399:64)↵    at executeTemplate (http://localhost:37951/care01-ng/dist/care01-ng/vendor.js:38614:9)"__proto__: Error__proto__: Object
custom-error-handler.ts:12 TypeError: Cannot read property 'time' of undefined
    at NgxTimepickerTimeControlComponent.push../node_modules/ngx-material-timepicker/__ivy_ngcc__/fesm5/ngx-material-timepicker.js.NgxTimepickerTimeControlComponent.setAvailableTime (ngx-material-timepicker.js:3157)
    at NgxTimepickerTimeControlComponent.push../node_modules/ngx-material-timepicker/__ivy_ngcc__/fesm5/ngx-material-timepicker.js.NgxTimepickerTimeControlComponent.ngOnChanges (ngx-material-timepicker.js:3049)
    at NgxTimepickerTimeControlComponent.wrapOnChangesHook_inPreviousChangesStorage (core.js:19348)
    at callHook (core.js:2919)
    at callHooks (core.js:2885)
    at executeCheckHooks (core.js:2820)
    at selectIndexInternal (core.js:6215)
    at Module.ɵɵadvance (core.js:6194)
    at NgxTimepickerFieldComponent_Template (ngx-material-timepicker.js:2984)
    at executeTemplate (core.js:7575)
```

**Comment by Agranom** [comment]
The issue is fixed. Pls update to the latest version
