### ISSUE TITLE
ERROR Error: A Timepicker can only be associated with a single input.

### ISSUE THREAD

**Issue by pugazhdevan** [Agranom/ngx-material-timepicker#412]
**Detail Error** : core.mjs:6484 ERROR Error: A Timepicker can only be associated with a single input.
    at NgxMaterialTimepickerComponent.registerInput (ngx-material-timepicker.js:872:1)
    at TimepickerDirective.registerTimepicker (ngx-material-timepicker.js:1151:1)
    at TimepickerDirective.set timepicker [as timepicker] (ngx-material-timepicker.js:1086:1)
    at Object.ngOnChangesSetInput [as setInput] (core.mjs:1517:5)
    at setInputsForProperty (core.mjs:10976:17)
    at elementPropertyInternal (core.mjs:10023:9)
    at Module.ɵɵproperty (core.mjs:14442:9)
    at SearchComponent_div_19_Template (search.component.html:74:43)
    at executeTemplate (core.mjs:9618:9)
    at refreshView (core.mjs:9484:13)

I am trying to use two time picker in the component and i am using different Id for both the picker

**Comment by zorkind** [comment]
I am having this exact issue with the 13.1.1 version, whats going on with this?
